<?php

/**
 * @file
 * myblock.module
 *
 */

/**
 * Implements hook_block_info()
 */

function myblock_block_info() {
  
  $blocks['myblock'] = array(
    'info' => t('My Custom Block'),
   
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */

function myblock_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'myblock':
      $block['subject'] = t('This is Allen custom block');
      $block['content'] = "test";
      break;
  }
  return $block;
}